### ISSUE TITLE
SwiftYOLO config

### ISSUE THREAD

**Issue by dosemeion** [Seeed-Studio/sscma-model-zoo#11]
### Describe your issue

file not found：https://github.com/Seeed-Studio/sscma-model-zoo/blob/main/docs/en/configs/yolov5/swift_yolo_shuff_1xb16_300e_coco.py

### Expected behavior

share config

### Validations

- [X] Read SSCMA Model Zoo and SSCMA docs.
- [X] There has no simliar issue or pull request.

**Comment by Pillar1989** [comment]
@LynnL4

**Comment by LynnL4** [comment]
Hi, All config files will be placed under this repository, thanks!
https://github.com/Seeed-Studio/ModelAssistant/tree/main/configs
